apiVersion: v1
kind: ConfigMap
metadata:
  name: truva-config
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      tls:
        enabled: true
        cert_file: "/etc/tls/tls.crt"
        key_file: "/etc/tls/tls.key"
    
    logging:
      level: "info"
      format: "json"
      output: "stdout"
    
    log_aggregation:
      enabled: true
      signoz:
        enabled: true
        endpoint: "https://signoz.monitoring.svc.cluster.local:4317"
        batch_size: 500
        flush_interval: "30s"
        timeout: "30s"
    
    kubernetes:
      in_cluster: true
      namespace: "truva-prod"
    
    ui:
      enabled: true
      path: "/ui"
    
    sync:
      enabled: true
      interval: "60s"
      batch_size: 100
      timeout: "30s"
    
    monitoring:
      enabled: true
      metrics_path: "/metrics"
      health_path: "/health"
      ready_path: "/ready"
    
    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst: 100
      websocket:
        connections_per_ip: 50
        message_rate: 500