apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: truva-prod

resources:
- ../../base
- ingress.yaml
- hpa.yaml
- pdb.yaml
- networkpolicy.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

replicas:
- name: truva
  count: 5

images:
- name: truva
  newTag: v1.0.0

commonLabels:
  environment: production