apiVersion: v1
kind: ConfigMap
metadata:
  name: truva-config
  labels:
    app: truva
data:
  config.yaml: |
    server:
      host: "0.0.0.0"
      port: 8080
      tls:
        enabled: false
        cert_file: ""
        key_file: ""
        ca_file: ""
    
    logging:
      level: "info"
      format: "json"
      output: "stdout"
    
    log_aggregation:
      enabled: true
      signoz:
        enabled: true
        endpoint: "http://signoz-otel-collector:4317"
        api_key: ""
        batch_size: 100
        flush_interval: "5s"
        timeout: "10s"
    
    kubernetes:
      in_cluster: true
      config_path: ""
      namespace: "default"
    
    ui:
      enabled: true
      path: "/ui"
      static_path: "./ui/dist"
    
    sync:
      enabled: true
      interval: "30s"
      batch_size: 50
      timeout: "10s"
    
    monitoring:
      enabled: true
      metrics_path: "/metrics"
      health_path: "/health"
      ready_path: "/ready"
    
    secrets:
      encryption_key: "your-32-byte-encryption-key-here"
    
    rate_limiting:
      enabled: true
      requests_per_minute: 100
      burst: 10
      websocket:
        connections_per_ip: 5
        message_rate: 50