apiVersion: apps/v1
kind: Deployment
metadata:
  name: truva
  labels:
    app: truva
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: truva
  template:
    metadata:
      labels:
        app: truva
        version: v1
    spec:
      serviceAccountName: truva
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        fsGroup: 1001
      containers:
      - name: truva
        image: mcr.microsoft.com/dotnet/samples:aspnetapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: TRUVA_ENV
          value: "production"
        - name: GIN_MODE
          value: "release"
        - name: ASPNETCORE_URLS
          value: "http://+:8080"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        # Health checks disabled for simple dotnet app
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: http
        # readinessProbe:
        #   httpGet:
        #     path: /ready
        #     port: http
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
        volumeMounts:
        - name: app-src
          mountPath: /app/src
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: app-src
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - key: "kubernetes.io/arch"
        operator: "Equal"
        value: "amd64"
        effect: "NoSchedule"