apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- serviceaccount.yaml
- configmap.yaml

commonLabels:
  app: truva
  version: v1

images:
- name: truva
  newTag: latest

replicas:
- name: truva
  count: 3