apiVersion: v1
kind: Service
metadata:
  name: truva
  labels:
    app: truva
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: truva